basePath: /
definitions:
  model.AddFileRequest:
    properties:
      url:
        type: string
    type: object
  model.ErrorResponse:
    properties:
      code:
        type: integer
    type: object
  model.TaskStatusResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Сервис архивации файлов по ссылкам
  title: Go Zipper API
  version: "1.0"
paths:
  /tasks/{id}/addFile:
    post:
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: string
      - description: fileInfoJson
        in: body
        name: fileInfo
        required: true
        schema:
          $ref: '#/definitions/model.AddFileRequest'
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
  /tasks/{id}/status:
    get:
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TaskStatusResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
  /tasks/createTask:
    post:
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
swagger: "2.0"
